import type { Book } from "../types"

export const mockBooks: Book[] = [
  { id: "1", title: "The Great Gatsby", author: "F. Scott Fitzgerald", category: "Fiction", shelf: "A1", status: "Available", image: "https://picsum.photos/seed/1/200/300" },
  { id: "2", title: "To Kill a Mockingbird", author: "Harper Lee", category: "Fiction", shelf: "A2", status: "Not Available", image: "https://picsum.photos/seed/2/200/300" },
  { id: "3", title: "Sapiens", author: "Yuval Noah Harari", category: "Non-Fiction", shelf: "B1", status: "Available", image: "https://picsum.photos/seed/3/200/300" },
  { id: "4", title: "The Catcher in the Rye", author: "J.D. Salinger", category: "Fiction", shelf: "A3", status: "Available", image: "https://picsum.photos/seed/4/200/300" },
  { id: "25", title: "Not Letting Go", author: "A. S. Daniels", category: "Romance", shelf: "C9", status: "Available", image: "https://picsum.photos/seed/25/200/300", ownerId: "user_4" },
  { id: "26", title: "Love Life", author: "Rita Morgan", category: "Romance", shelf: "C10", status: "Available", image: "https://picsum.photos/seed/26/200/300", ownerId: "user_5" },
  { id: "27", title: "Love Language", author: "E. Chapman", category: "Romance", shelf: "C11", status: "Available", image: "https://picsum.photos/seed/27/200/300", ownerId: "user_6" },
  { id: "5", title: "Pride and Prejudice", author: "Jane Austen", category: "Romance", shelf: "C1", status: "Available", image: "https://picsum.photos/seed/5/200/300", ownerId: "user_1" },
  { id: "6", title: "The Notebook", author: "Nicholas Sparks", category: "Romance", shelf: "C2", status: "Not Available", image: "https://picsum.photos/seed/6/200/300", ownerId: "user_2" },
  { id: "7", title: "1984", author: "George Orwell", category: "Fiction", shelf: "A4", status: "Available", image: "https://picsum.photos/seed/7/200/300" },
  { id: "8", title: "Becoming", author: "Michelle Obama", category: "Biography", shelf: "B2", status: "Available", image: "https://picsum.photos/seed/8/200/300" },
  { id: "9", title: "The Alchemist", author: "Paulo Coelho", category: "Fiction", shelf: "A5", status: "Available", image: "https://picsum.photos/seed/9/200/300" },
  { id: "10", title: "Me Before You", author: "Jojo Moyes", category: "Romance", shelf: "C3", status: "Not Available", image: "https://picsum.photos/seed/10/200/300" },
  { id: "11", title: "Educated", author: "Tara Westover", category: "Biography", shelf: "B3", status: "Available", image: "https://picsum.photos/seed/11/200/300" },
  { id: "12", title: "Atomic Habits", author: "James Clear", category: "Self-Help", shelf: "D1", status: "Available", image: "https://picsum.photos/seed/12/200/300" },
  { id: "13", title: "The Art of Letting Go", author: "R. K. Sharma", category: "Self-Help", shelf: "D2", status: "Available", image: "https://picsum.photos/seed/13/200/300" },
  { id: "14", title: "The Art of Being Average", author: "S. P. Rao", category: "Self-Help", shelf: "D3", status: "Available", image: "https://picsum.photos/seed/14/200/300" },
  { id: "15", title: "The Art of Being Introvert", author: "L. K. Mehta", category: "Self-Help", shelf: "D4", status: "Not Available", image: "https://picsum.photos/seed/15/200/300" },
  { id: "16", title: "Love in the Time of Code", author: "A. N. Writer", category: "Romance", shelf: "C4", status: "Available", image: "https://picsum.photos/seed/16/200/300", ownerId: "user_3" },
  { id: "17", title: "A Midnight Promise", author: "Lena Hart", category: "Romance", shelf: "C5", status: "Available", image: "https://picsum.photos/seed/17/200/300", ownerId: "user_1" },
  { id: "18", title: "The Last Love Letter", author: "Jonas Reed", category: "Romance", shelf: "C6", status: "Available", image: "https://picsum.photos/seed/18/200/300" },
  { id: "19", title: "Whispers on the Pier", author: "Elena Rose", category: "Romance", shelf: "C7", status: "Available", image: "https://picsum.photos/seed/19/200/300" },
  { id: "20", title: "The Engineer's Heart", author: "R. K. Alvarez", category: "Romance", shelf: "C8", status: "Available", image: "https://picsum.photos/seed/20/200/300" },
  { id: "21", title: "Across the Quiet Sea", author: "M. L. Hargrove", category: "Fiction", shelf: "A6", status: "Available", image: "https://picsum.photos/seed/21/200/300" },
  { id: "22", title: "A Better Tomorrow", author: "Samira Patel", category: "Non-Fiction", shelf: "B4", status: "Available", image: "https://picsum.photos/seed/22/200/300" },
  { id: "23", title: "Handbook for New Habits", author: "Jon Fletcher", category: "Self-Help", shelf: "D5", status: "Available", image: "https://picsum.photos/seed/23/200/300" },
  { id: "24", title: "The Silent Observer", author: "Nina Alvarez", category: "Mystery", shelf: "E1", status: "Available", image: "https://picsum.photos/seed/24/200/300" },
  { id: "28", title: "The art of overthinking", author: "sharan kumbhar", category: "self", shelf: "User", status: "Available", image: "https://m.media-amazon.com/images/I/81sYJws8LkL._UF1000,1000_QL80_.jpg" },
  { id: "29", title: "Hollow night", author: "siddesh halgekar", category: "lust", shelf: "User", status: "Available", image: "https://upload.wikimedia.org/wikipedia/en/thumb/0/04/Hollow_Knight_first_cover_art.webp/250px-Hollow_Knight_first_cover_art.webp.png" },
]

// No admin requests in the simplified app.
